apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
    {{- include "palworld.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.gamePort }}
      targetPort: game
      protocol: UDP
      name: game
    - port: {{ .Values.service.queryPort }}
      targetPort: query
      protocol: UDP
      name: query
    {{- if .Values.config.env.RCON_ENABLED }}
    - port: {{ .Values.service.rconPort }}
      targetPort: rcon
      protocol: TCP
      name: rcon
    {{- end }}
  selector:
    {{- include "palworld.selectorLabels" . | nindent 4 }}
